# External Gems
plugins: 						[jekyll-paginate]

# Exclude build files
exclude: ["node_modules", "gulpfile.js", "package.json", "themes"]

# Site Settings
title: 						"Miki Ishijima Blog"
description: 			"趣味のゲームやプログラミング、レビューなど個人イシジマミキにより近しい内容を書いています。普遍的なデザインの話はThe Marsknowledge Blogで。"
email: 						"woops.mirai@gmail.com"
baseurl: 					""
url: 					    "http://blog.mikiishijima.com/"
content_url: 	    "/content"
logourl: 				  "/assets/img/bloglogo.jpg"
paginate: 				10
excerpt_separator: "<!--more-->"

# Author Settings
author_name: 				"Miki Ishijima"
author_url: 				"http://mikiishijima.com/"
author_bio: 				"デザインワーク、ソフトウェア開発のワークフロー、デザイン自体の考え方に関する著書を持つ。2013年にザ・マーズナレッジ株式会社設立。"
author_email: 			"woops.mirai@gmail.com"
author_image: 			"/content/images/about/woopsdez-owner-sq.jpg"


# Social Settings
twitter_url: 				"http://twitter.com/woopsdez"
facebook_url: 			"http://facebook.com/woopsdez"
github_url:  				"http://github.com/woopsdez"


# Theme Settings
theme_disqus_shortname: 	""
theme_google_comments: 		true
theme_analytics_id: 		"UA-413655-12"
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty
