# External Gems
gems: 						[jekyll-paginate]

# Exclude build files
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Site Settings
title: 						"Miki Ishijima Blog"
description: 			"イシジマミキ ブログ"
email: 						"woops.mirai@gmail.com"
baseurl: 					"http://blog.mikiishijima.com"
url: 					    "http://blog.mikiishijima.com"
content_url: 	    "/content"
logourl: 				  "/assets/img/bloglogo.jpg"
fa-logo: 					"fa-bookmark-o"
paginate: 				5


# Author Settings
author_name: 				"Miki Ishijima"
author_url: 				"http://mikiishijima.com/"
author_bio: 				"デザインワーク、ソフトウェア開発のワークフロー、デザイン自体の考え方に関する著書を持つ。2013年にザ・マーズナレッジ株式会社設立。"
author_email: 			"woops.mirai@gmail.com"
author_image: 			"https://dl.dropboxusercontent.com/u/797976/profile/woopsdez-owner-sq.jpg"


# Social Settings
twitter_url: 				"http://twitter.com/woopsdez"
facebook_url: 			""
github_url:  				"http://github.com/woopsdez"
youtube_url:  			""
dribbble_url:  			"http://dribbble.com/woopsdez"
googleplus_url: 		""
instagram_url:  		""
pinterest_url:  		""
linkedin_url:  			""


# Theme Settings
theme_disqus_shortname: 	""
theme_google_comments: 		true
theme_analytics_id: 		"UA-413655-12"
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
# permalink: 					/:title/
permalink: 					pretty